name: gic
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.9
  - pytorch=2.4.0
  - pytorch-cuda=12.1
  - torchvision=0.19.0
  - torchaudio=2.4.0
  - pip:
      - dearpygui==1.10.1
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - lpips==0.1.4
      - mmcv==2.1.0
      - ninja==1.11.1.1
      - open3d==0.18.0
      - opencv-python==4.9.0.80
      - plyfile==1.0.3
      - scipy==1.12.0
      - taichi==1.2.0
      - torch-scatter==2.1.2
      - tqdm==4.66.1
      - trimesh==4.1.0
      - einops==0.7.0
      - git+https://github.com/jukgei/diff-gaussian-rasterization.git@b1e1cb83e27923579983a9ed19640c6031112b94
      - git+https://gitlab.inria.fr/bkerbl/simple-knn.git
      - git+https://github.com/facebookresearch/pytorch3d.git